### ISSUE TITLE
Updated Grafana dashboard

### ISSUE THREAD

**Issue by eljohnson92** [Derek-K/telegraf-speedtest#5]
Hello @Derek-K, I have made some updates to your grafana dashboard to add a few metrics(packet loss, total test upload/download bytes in the past month) that I was hoping to contribute back to your dashboard for review, do you have a git repo I can make a PR against with my updated json to have these looked at?

**Comment by Derek-K** [comment]
Hi @eljohnson92, I did look into including the packet loss metric initially, but after consulting with OOKLA support, not all servers support 'packet loss' as part of the test and get 'not available' in return.

As for total test upload/download bytes, IMHO it is pretty easy to figure out by # of tests (IIRC # of bytes upload/download is constant). If one wants to see the % of byte use for speedtest per month compare to their monthly traffic, it should be doable by a simple equation. On top of that, the % should be pretty low, unless a dedicated interface is only used for speedtest (??).

**Comment by eljohnson92** [comment]
I have my dashboard set to treat no value as 0 for packet loss. If you are not interested in my updates that is also fine, just figured I would try and contribute back if you were interested. Feel free to close this if you'd like.

**Comment by risb0r** [comment]
![image](https://user-images.githubusercontent.com/16470277/95745310-95c73480-0ce0-11eb-964c-1e93493d2cc0.png)
Just sharing what I got.

**Comment by Derek-K** [comment]
@eljohnson92 do you happen to know risb0r?

Anyway, there are a few concerns I have (not directly at you but more on the latest pull request by risb0r)...
1) As I have mentioned to others before, I do not like to include "--accept-license --accept-gdpr" because it is really user's responsibility to accept OOKLA's license agreements before using their binaries instead of bypassing it on the first run.
2) IMHO, for "no value" on packet loss, it should be a NULL value instead of 0.
3) Dislike branding of my original work, which is one of the concerns I have initially when I publish my work.
